# Project runs on this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
    - "last 2 versions"
    - "ie >= 9"
    - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
    html:
        - "src/**/*.html"
    ignore:

# Gulp will reference these paths when it copies files
PATHS: 
    # Path to dist folder
    dist: "dist"
    # Path to static assets that aren't images, CSS, or javascript
    assets:
        - "src/assets/**/*"
        - "!src/assets/{img,js,scss/**/*}"
    sass:
        - "bower_components/bootstrap-sass/assets/stylesheets"
    javascript:
        - "bower_components/jquery/dist/jquery.js"
        - "bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js"
        - "src/assets/js/!(app).js"
        - "src/assets/js/app.js"



